"""create user_values table

Revision ID: d8f76e9ea651
Revises: 
Create Date: 2024-06-28 23:46:02.759513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f76e9ea651'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_values_id'), 'user_values', ['id'], unique=False)
    op.create_index(op.f('ix_user_values_user_id'), 'user_values', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_values_user_id'), table_name='user_values')
    op.drop_index(op.f('ix_user_values_id'), table_name='user_values')
    op.drop_table('user_values')
    # ### end Alembic commands ###
